[[language]]
comment-token = '--'
file-types = ['cabal']
language-servers = ['haskell-language-server']
name = 'cabal'
roots = ['cabal.project', 'Setup.hs']
scope = 'source.cabal'

[language.indent]
tab-width = 2
unit = '  '
