[[language]]
comment-token = '#'
file-types = ['cr']
grammar = 'ruby'
language-servers = ['crystalline']
name = 'crystal'
roots = ['shard.yml', 'shard.lock']
scope = 'source.cr'

[language.indent]
tab-width = 2
unit = '  '
