[[language]]
auto-format = true
file-types = ['css', 'scss']
injection-regex = 'css'
language-servers = ['vscode-css-language-server']
name = 'css'
scope = 'source.css'

[language.block-comment-tokens]
end = '*/'
start = '/*'

[language.indent]
tab-width = 2
unit = '  '
