[[language]]
comment-token = '#'
file-types = ['Dockerfile', {glob = 'Dockerfile'}, {glob = 'Dockerfile.*'}, 'dockerfile', {glob = 'dockerfile'}, {glob = 'dockerfile.*'}, 'Containerfile', {glob = 'Containerfile'}, {glob = 'Containerfile.*'}, 'containerfile', {glob = 'containerfile'}, {glob = 'containerfile.*'}]
injection-regex = 'docker|dockerfile'
language-servers = ['docker-langserver']
name = 'dockerfile'
roots = ['Dockerfile', 'Containerfile']
scope = 'source.dockerfile'

[language.indent]
tab-width = 2
unit = '  '
