[[language]]
comment-token = '#'
file-types = ['ex', 'exs', {glob = 'mix.lock'}]
injection-regex = '(elixir|ex)'
language-servers = ['elixir-ls']
name = 'elixir'
roots = ['mix.exs', 'mix.lock']
scope = 'source.elixir'
shebangs = ['elixir']

[language.indent]
tab-width = 2
unit = '  '
