[[language]]
comment-token = '#'
grammar = 'gitignore'
injection-regex = 'git-ignore'
name = 'git-ignore'
scope = 'source.gitignore'

[[language.file-types]]
glob = '.gitignore_global'

[[language.file-types]]
glob = 'git/ignore'

[[language.file-types]]
glob = '.ignore'

[[language.file-types]]
glob = 'CODEOWNERS'

[[language.file-types]]
glob = '.config/helix/ignore'

[[language.file-types]]
glob = '.helix/ignore'

[[language.file-types]]
glob = '.*ignore'
