[[language]]
comment-token = '#'
file-types = [{glob = 'Makefile'}, {glob = 'makefile'}, 'make', 'mk', 'mak', {glob = 'GNUmakefile'}, {glob = 'OCamlMakefile'}]
injection-regex = '(make|makefile|Makefile|mk)'
name = 'make'
scope = 'source.make'
shebangs = ['make', 'gmake']

[language.indent]
tab-width = 4
unit = '	'
