[[language]]
file-types = ['md', 'livemd', 'markdown', 'mdx', 'mkd', 'mkdn', 'mdwn', 'mdown', 'markdn', 'mdtxt', 'mdtext', 'workbook', {glob = 'PULLREQ_EDITMSG'}]
injection-regex = 'md|markdown'
language-servers = ['marksman', 'markdown-oxide']
name = 'markdown'
roots = ['.marksman.toml']
scope = 'source.md'

[language.block-comment-tokens]
end = '-->'
start = '<!--'

[language.indent]
tab-width = 2
unit = '  '
