[[language]]
comment-token = '//'
file-types = ['pony']
injection-regex = 'pony'
name = 'ponylang'
roots = ['corral.json', 'lock.json']
scope = 'source.pony'

[language.block-comment-tokens]
end = '*/'
start = '/*'

[language.indent]
tab-width = 2
unit = '  '
