[[language]]
comment-token = '#'
file-types = ['py', 'pyi', 'py3', 'pyw', 'ptl', 'rpy', 'cpy', 'ipy', 'pyt', {glob = '.python_history'}, {glob = '.pythonstartup'}, {glob = '.pythonrc'}, {glob = '*SConstruct'}, {glob = '*SConscript'}, {glob = '*sconstruct'}]
injection-regex = 'py(thon)?'
language-servers = ['ruff', 'jedi', 'pylsp']
name = 'python'
roots = ['pyproject.toml', 'setup.py', 'poetry.lock', 'pyrightconfig.json']
scope = 'source.python'
shebangs = ['python', 'uv']

[language.indent]
tab-width = 4
unit = '    '
