[[language]]
comment-tokens = ['#', "#'"]
file-types = ['r', 'R', {glob = '.Rprofile'}, {glob = 'Rprofile.site'}, {glob = '.RHistory'}]
injection-regex = '(r|R)'
language-servers = ['r']
name = 'r'
scope = 'source.r'
shebangs = ['r', 'R']

[language.indent]
tab-width = 2
unit = '  '
