[[language]]
comment-tokens = ['//', '///']
file-types = ['spade']
injection-regex = 'spade'
language-servers = ['spade-language-server']
name = 'spade'
roots = ['swim.toml']
scope = 'source.spade'

[language.auto-pairs]
'"' = '"'
'(' = ')'
'<' = '>'
'[' = ']'
'{' = '}'

[[language.block-comment-tokens]]
end = '*/'
start = '/*'

[[language.block-comment-tokens]]
end = '*/'
start = '/**'

[language.indent]
tab-width = 4
unit = '    '
