[[language]]
comment-token = '//'
file-types = ['sw']
injection-regex = 'sway'
language-servers = ['forc']
name = 'sway'
roots = ['Forc.toml', 'Forc.lock']
scope = 'source.sway'

[language.indent]
tab-width = 4
unit = '    '
