[[language]]
comment-token = '//'
file-types = ['thrift']
name = 'thrift'
scope = 'source.thrift'

[language.block-comment-tokens]
end = '*/'
start = '/*'

[language.indent]
tab-width = 2
unit = '  '
