[[language]]
file-types = ['xml', 'mobileconfig', 'plist', 'xib', 'storyboard', 'svg', 'xsd', 'gml', 'xaml', 'gir', 'rss', 'atom', 'opml', 'policy', 'ascx', 'axml', 'axaml', 'bpmn', 'cpt', 'csl', 'csproj.user', 'dita', 'ditamap', 'dtml', 'fxml', 'iml', 'isml', 'jmx', 'launch', 'menu', 'mxml', 'nuspec', 'osc', 'osm', 'pt', 'publishsettings', 'pubxml', 'pubxml.user', 'rbxlx', 'rbxmx', 'rng', 'shproj', 'tld', {glob = '*.tm[Tt]heme'}, 'tmx', 'vbproj.user', 'vcxproj', 'vcxproj.filters', 'wsdl', 'wxi', 'wxs', 'xbl', 'xlf', 'xliff', 'xpdl', 'xul', 'xoml', 'musicxml', 'glif', 'ui', 'sublime-snippet', 'xsl', 'mpd', 'smil']
injection-regex = 'xml'
name = 'xml'
scope = 'source.xml'

[language.auto-pairs]
'"' = '"'
"'" = "'"
'(' = ')'
'<' = '>'
'[' = ']'
'{' = '}'

[language.block-comment-tokens]
end = '-->'
start = '<!--'

[language.indent]
tab-width = 2
unit = '  '
